### ISSUE TITLE
New TheCodingLove website

### ISSUE THREAD

**Issue by patricevoss** [simonmeusel/codingapp#2]
Since TheCodingLove got a new website, the /random page doesn't exist anymore.

The app will just shows a black screen because it doesn't find anything.

**Comment by qmnl** [comment]
Yes, the new release seems to no longer have a endpoint for a random post. Instead it sends a random a link to a random post right in the initial response. But it should't be toooo hard to adopt to that.

**Comment by qmnl** [comment]
Furthermore obviously the selectors for image, author ... have changed

**Comment by patricevoss** [comment]
I trust in you! I need it!

**Comment by qmnl** [comment]
Already finished LuL

**Comment by qmnl** [comment]
I'm gonna run the build and stuff

653fc6b496a063932752de86c191bbc22667a74e

**Comment by patricevoss** [comment]
Perfect, I can't work without it

**Comment by qmnl** [comment]
xD

The first post is always gonna be the first post ever I think, but then it's random

**Comment by patricevoss** [comment]
That's okay

Thanks for the quick fix!

**Comment by qmnl** [comment]
CI/CD finished the build for the guy in the tower: https://github.com/simonmeusel/codingapp/releases/tag/0.3.0
